#!/bin/bash -xe

. .travis.env

REPO=$TRAVIS_REPO_SLUG

if [[ "${TRAVIS_PULL_REQUEST}" != "false" ]]; then
    echo "Github page deployment not performed for pull requests"
    exit 0
# Push to a different repo if the branch name begins with 'itb.'
elif [[ "${TRAVIS_BRANCH}" =~ itb\..* ]]; then
    ENCRYPTED_FILE="$ITB_ENCRYPTED_FILE"
    KEY="$ITB_KEY"
    IV="$ITB_IV"
    REPO="$ITB_REPO"

    # Change site info for ITB documentation
    sed -i 's/\(site_name: .*\)/\1 \(ITB\)/' mkdocs.yml
    sed -i 's/\(.*_url: .*\/docs\)\//\1-itb\//' mkdocs.yml
    sed -i 's/google_analytics.*//' mkdocs.yml

    # Change color of ITB nav bar
    sed -i 's/\(extra_css:\)/\1\n  - css\/itb.css/' mkdocs.yml
    CSS_DIR='docs/css/'
    mkdir -p $CSS_DIR
    cp ci/itb.css $CSS_DIR

    # Prevent site crawling; requires theme custom_dir set to osgthedocs
    THEME_DIR='osgthedocs'
    mkdir -p $THEME_DIR
    cp ci/no-robots.html $THEME_DIR/main.html
elif [[ "${TRAVIS_BRANCH}" != "master" ]]; then
    echo "Github page deployment not performed for non-master, non-ITB branch"
    exit 0
fi

# We can't deploy if any of these vars are empty
for variable in "$KEY" "$IV" "$REPO" "$ENCRYPTED_FILE"; do
    if [ -z "$variable" ]; then
        echo "ERROR: Found empty KEY, IV, REPO, or ENCRYPTED_FILE variable. Exiting."
        exit 1
    fi
done

openssl aes-256-cbc -K "$KEY" -iv "$IV" -in "$ENCRYPTED_FILE" -out deploy-key -d

chmod 600 deploy-key
eval `ssh-agent -s`
ssh-add deploy-key
git config user.name "Automatic Publish"
git config user.email "goc@opensciencegrid.org"
git remote add gh-token "git@github.com:$REPO.git";
git fetch gh-token && git fetch gh-token gh-pages:gh-pages
echo "Pushing to github"
PYTHONPATH=src/ mkdocs gh-deploy -v --clean --remote-name gh-token
