#!/bin/bash
realpath () {
    python -c "import sys, os; sys.stdout.write(os.path.realpath('''$1''')+'\n')"
}
cd "$(dirname "$(realpath $0)")"
topdir=$(git rev-parse --show-superproject-working-tree)  # use what we're a submodule of
if [[ -z $topdir ]]; then
    # not a submodule
    topdir=$(git rev-parse --show-toplevel)
fi
cd "$topdir"
PYTHONPATH=$(pwd)/src
export PYTHONPATH
exec mkdocs serve "$@"
