#!/bin/bash -x

PYTHONPATH=src/ mkdocs serve --verbose --strict &
timeout 30 bash -c 'until (echo > /dev/tcp/localhost/8000); do sleep 0.5; done' > /dev/null 2>&1
linkchecker --config=ci/linkchecker.config 'http://localhost:8000/'

# cleanup after ourselves
linkchecker_rc=$?
pkill mkdocs
exit $linkchecker_rc
